//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovitaResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messaggi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messaggi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnovitaResource.Messaggi", typeof(Messaggi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile creare l&apos;articolo {0}. {1}.
        /// </summary>
        public static string ImpossibileCreareArticolo {
            get {
                return ResourceManager.GetString("ImpossibileCreareArticolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile creare la distinta base {0}. {1}.
        /// </summary>
        public static string ImpossibileCreareBom {
            get {
                return ResourceManager.GetString("ImpossibileCreareBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile stampare l&apos;etichetta.
        /// </summary>
        public static string ImpossibileStampare {
            get {
                return ResourceManager.GetString("ImpossibileStampare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La revisione {0} non e&apos; un numero valido.
        /// </summary>
        public static string RevisioneNoNumero {
            get {
                return ResourceManager.GetString("RevisioneNoNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare la riga da cancellare.
        /// </summary>
        public static string SelezionareRigaCancellare {
            get {
                return ResourceManager.GetString("SelezionareRigaCancellare", resourceCulture);
            }
        }
    }
}
